# Generated by Django 4.2.4 on 2024-07-24 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datas',
            old_name='Conatct',
            new_name='Contact',
        ),
    ]
